In [1]:
import pickle
import pandas as pd

In [2]:
# 读取描述符，需要确保描述符的顺序和拟合训练时一致（列名不重要）
raw_data=pd.read_csv('./oled-ml-202411216446.csv')
data = raw_data.iloc[:, 1:]
data

,Unnamed: 1,Unnamed: 2,repr,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 505,Unnamed: 506,Unnamed: 507,Unnamed: 508,Unnamed: 509,Unnamed: 510,Unnamed: 511,Unnamed: 512,Unnamed: 513,Unnamed: 514
0,2.582280,2.7523,0.007372,-0.707371,-0.839814,0.091497,0.169695,-1.798712,0.391467,1.066125,...,1.068467,-0.150287,0.176141,-2.679623,1.178129,0.265743,-0.267961,1.928361,0.756363,-2.096006
1,2.564511,2.7528,0.241694,-0.830182,-0.879442,0.132933,0.150280,-1.762729,0.404894,1.160647,...,1.101126,-0.251464,0.088440,-2.623930,1.196807,0.344765,-0.359192,1.855635,0.683707,-2.136585
2,2.469571,2.7041,0.092091,-0.835394,-0.712946,0.113213,0.223132,-1.679872,0.448917,0.986751,...,1.062931,-0.228969,0.152873,-2.616601,1.154404,0.399090,-0.495608,1.965849,0.803262,-2.162809
3,2.487312,2.7034,0.051319,-0.707674,-0.941726,0.118063,0.138578,-1.681332,0.371051,0.932958,...,1.049977,-0.046936,0.010446,-2.660266,1.153250,0.402108,-0.364429,1.965905,0.545995,-2.136857
4,2.435611,2.6894,-0.052061,-0.685750,-0.804297,0.068692,0.164218,-1.802564,0.441224,0.854063,...,1.004910,-0.031467,-0.005567,-2.664368,1.129589,0.272740,-0.344575,1.978893,0.589597,-2.131898

In [3]:
# 加载模型
with open('./ET-T1-slope.pkl','rb') as f:
    model=pickle.load(f)

# 预测
y_pred = model.predict(data.to_numpy())


for i in y_pred:
    print(i)

2.683252449054333
2.679191031822751
2.6657219944946067
2.679349794358105
2.669745582441397